import './globals.css'
import { Inter } from 'next/font/google'

import 'bootstrap/dist/css/bootstrap.min.css';
import ReduxProvider from '@/store/storeProvider'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from '@/common/components/header';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <div className='h-screen'>
        <Header />
        <ReduxProvider >
        {children}
        </ReduxProvider>
        <ToastContainer />
        </div>
        </body>
        
    </html>
  )
}
